spring:
  application:
    name: microservice
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:db}:${POSTGRES_PORT:5432}/${POSTGRES_DB:coffee_soul}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
