services:
  microservice:
    build: .
    depends_on:
      db:
        condition: service_healthy
      database-seeding:
        condition: service_completed_successfully
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: coffee_soul
      POSTGRES_USER: ${POSTGRES_USER:-}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-}
